services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=test'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=root_password'
    ports:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: